version: '2'
services:
  app:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - db
    env_file:
      - .env
  db:
    image: postgres:9.4.0
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD