default: &default
  adapter: postgresql
  database: es_page
  encoding: unicode
  username: postgres
  host:     <%= ENV['DATABASE_HOST'] %>
  port:     <%= ENV['DATABASE_PORT'] %>

development:
  <<: *default
  database: es_page_development

test:
  <<: *default
  database: es_page_test

production:
  <<: *default
  database: es_page_production